### ISSUE TITLE
More species that it was before

### ISSUE THREAD

**Issue by mfreidin1975** [AstrobioMike/bit#12]
After running bit to combine taxonomy, I ended up with more taxa than I had before.
i.e. after running bracken, I had about 7000 species, but after running bit, there are ~11,000.
Is it something expected?

I used bit-combine-bracken-and-add-lineage and followed the guidance from here
https://hackmd.io/@astrobiomike/bit-bracken-combine-and-add-lineage

**Comment by AstrobioMike** [comment]
heya @mfreidin1975 :)

First, sorry for the slow response, my email suddenly started sending my github issue notifications to spam :(

I haven't used this in a while, but i suspect it has to do with accession NCBI's taxonomy database at different times (like what was used for the initial kraken database vs when this was run). Or is it possible the 7,000 number comes from any given individual sample and there are more when looking at all of them? 

Would you be able/willing to send me your input data and info on the kraken taxonomy assignment that was done originally? Can send to MikeLee@bmsis.org if so. That would help me dig deeper

cheers :) 
-Mike
