### ISSUE TITLE
Feature request - Ability to download gene nucleotide sequences when using `bit-dl-ncbi-assemblies`

### ISSUE THREAD

**Issue by Sidduppal** [AstrobioMike/bit#15]
Hey @AstrobioMike thanks for this amazing tool. I have a small feature request.
I was wondering if it will be possible to update `bit-dl-ncbi-assemblies` where it can be used to download nucleotide sequences of genes (basically `ffn` files). Currently, `bit-dl-ncbi-assemblies` doesn't support the download of `ffn` (gene sequences in nucleotide format) but allows the download of `faa` files (gene sequences in amino acid format).
I'm happy to help in any way I can.
Thanks

**Comment by AstrobioMike** [comment]
Hi there, @Sidduppal!

Thanks for the request, can for sure add it if needed!

Not entirely sure which you mean right now though, can you tell me which for example from [this page](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/)?

We can already get the "*_cds_from_genomic.fna.gz" by specifying `-f nt_cds`, but are you referring to another one available there?

Thanks!

**Comment by AstrobioMike** [comment]
oh and i'll note that was only added as of the latest version, [v1.8.61](https://github.com/AstrobioMike/bit/releases/tag/v1.8.61), so maybe you have an older version which might be why you missed it if that is what is wanted :)

**Comment by Sidduppal** [comment]
Hi @AstrobioMike 

Looks like I was living in the past with an older version! Thanks for pointing that out and for your quick response. Much appreciated!

**Comment by AstrobioMike** [comment]
Awesome, thanks @Sidduppal!
